### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Manokii** [techchrism/valorant-api#1]
Hi, I'm very interested in this project, is there any example usage for this api?

**Comment by techchrism** [comment]
There are many projects online, here are a few of mine: 
 - https://github.com/techchrism/valorant-autorecord
 - https://github.com/techchrism/insomnia-plugin-valorant
 - https://github.com/techchrism/valorant-websocket-logger

**Comment by techchrism** [comment]
Haha I mistakenly closed this as I thought the issue was on the api-docs repo.

There are no examples yet as this is still a work in progress but to test basic functionality, my code looks something like this:
```javascript
const requestMaker = new NativeRequestMaker()
const api = new ValorantAPI(requestMaker, new LocalCredentialManager(requestMaker))

api.on('localInitialized', async (remoteApi: RemoteAPI<RemoteAPIDefaults>, initData) => {
    console.log(`Local initialization is ready`)

    const matchHistory = await remoteApi.getMatchHistory({startIndex: 0, endIndex: 1})
    console.log(matchHistory)
})
```

**Comment by Manokii** [comment]
Thank you so much!

> Haha I mistakenly closed this as I thought the issue was on the api-docs repo.
> 
> There are no examples yet as this is still a work in progress but to test basic functionality, my code looks something like this:
> 
> ```js
> const requestMaker = new NativeRequestMaker()
> const api = new ValorantAPI(requestMaker, new LocalCredentialManager(requestMaker))
> 
> api.on('localInitialized', async (remoteApi: RemoteAPI<RemoteAPIDefaults>, initData) => {
>     console.log(`Local initialization is ready`)
> 
>     const matchHistory = await remoteApi.getMatchHistory({startIndex: 0, endIndex: 1})
>     console.log(matchHistory)
> })
> ```
